spring:
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/newdb
      username: developer
      password: developer
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: fabriziotrupia1995@gmail.com
    password: FabTru1995
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jackson:
  serialization:
    fail-on-empty-beans: true