spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS:

redis:
  database:
  password:
  host:
  port:

---

environment: test
redis:
  host: localhost
  port: 6380
  password: